excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://LucyWang2014.github.io
title: d8agrl
tagline: thoughts on data from within venture capital
description: My awesome new site
paginate: 5